git clone https://android.googlesource.com/platform/build --depth 1 build/make  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/build/blueprint --depth 1 build/blueprint  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/build/kati --depth 1 build/kati  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/build/soong --depth 1 build/soong  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/art --depth 1 art  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/bootable/recovery --depth 1 bootable/recovery  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/compatibility/cdd --depth 1 compatibility/cdd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/cts --depth 1 cts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/dalvik --depth 1 dalvik  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/development --depth 1 development  -b android-9.0.0_r61 
git clone https://android.googlesource.com/device/common --depth 1 device/common  -b android-9.0.0_r61 
git clone https://android.googlesource.com/device/sample --depth 1 device/sample  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/aac --depth 1 external/aac  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/abi-compliance-checker --depth 1 external/abi-compliance-checker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/abi-dumper --depth 1 external/abi-dumper  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/adhd --depth 1 external/adhd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/adt-infra --depth 1 external/adt-infra  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/android-clat --depth 1 external/android-clat  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/androidplot --depth 1 external/androidplot  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/annotation-tools --depth 1 external/annotation-tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ant-glob --depth 1 external/ant-glob  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/antlr --depth 1 external/antlr  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/apache-commons-math --depth 1 external/apache-commons-math  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/apache-harmony --depth 1 external/apache-harmony  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/apache-http --depth 1 external/apache-http  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/apache-xml --depth 1 external/apache-xml  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/archive-patcher --depth 1 external/archive-patcher  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/autotest --depth 1 external/autotest  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/avb --depth 1 external/avb  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/bart --depth 1 external/bart  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/blktrace --depth 1 external/blktrace  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/boringssl --depth 1 external/boringssl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/bouncycastle --depth 1 external/bouncycastle  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/brotli --depth 1 external/brotli  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/bsdiff --depth 1 external/bsdiff  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/bzip2 --depth 1 external/bzip2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/caliper --depth 1 external/caliper  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/capstone --depth 1 external/capstone  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/cblas --depth 1 external/cblas  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/chromium-libpac --depth 1 external/chromium-libpac  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/chromium-trace --depth 1 external/chromium-trace  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/chromium-webview --depth 1 external/chromium-webview  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/clang --depth 1 external/clang  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/cmockery --depth 1 external/cmockery  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/cn-cbor --depth 1 external/cn-cbor  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/compiler-rt --depth 1 external/compiler-rt  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/conscrypt --depth 1 external/conscrypt  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/crcalc --depth 1 external/crcalc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/cros/system_api --depth 1 external/cros/system_api  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/curl --depth 1 external/curl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dagger2 --depth 1 external/dagger2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/deqp --depth 1 external/deqp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/desugar --depth 1 external/desugar  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/devlib --depth 1 external/devlib  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dexmaker --depth 1 external/dexmaker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dhcpcd-6.8.2 --depth 1 external/dhcpcd-6.8.2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dlmalloc --depth 1 external/dlmalloc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dng_sdk --depth 1 external/dng_sdk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dnsmasq --depth 1 external/dnsmasq  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/doclava --depth 1 external/doclava  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/droiddriver --depth 1 external/droiddriver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/drrickorang --depth 1 external/drrickorang  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/dtc --depth 1 external/dtc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/e2fsprogs --depth 1 external/e2fsprogs  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/easymock --depth 1 external/easymock  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/eigen --depth 1 external/eigen  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/elfutils --depth 1 external/elfutils  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/emma --depth 1 external/emma  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/error_prone --depth 1 external/error_prone  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/esd --depth 1 external/esd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/expat --depth 1 external/expat  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/eyes-free --depth 1 external/eyes-free  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/f2fs-tools --depth 1 external/f2fs-tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/fdlibm --depth 1 external/fdlibm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/fec --depth 1 external/fec  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/fio --depth 1 external/fio  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/flac --depth 1 external/flac  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/flatbuffers --depth 1 external/flatbuffers  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/fonttools --depth 1 external/fonttools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/freetype --depth 1 external/freetype  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/fsck_msdos --depth 1 external/fsck_msdos  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/gemmlowp --depth 1 external/gemmlowp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/gflags --depth 1 external/gflags  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/giflib --depth 1 external/giflib  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/glide --depth 1 external/glide  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/golang-protobuf --depth 1 external/golang-protobuf  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-api-services-storage --depth 1 external/google-api-services-storage  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-benchmark --depth 1 external/google-benchmark  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-breakpad --depth 1 external/google-breakpad  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-fonts/carrois-gothic-sc --depth 1 external/google-fonts/carrois-gothic-sc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-fonts/coming-soon --depth 1 external/google-fonts/coming-soon  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-fonts/cutive-mono --depth 1 external/google-fonts/cutive-mono  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-fonts/dancing-script --depth 1 external/google-fonts/dancing-script  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-styleguide --depth 1 external/google-styleguide  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/google-tv-pairing-protocol --depth 1 external/google-tv-pairing-protocol  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/googletest --depth 1 external/googletest  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/gptfdisk --depth 1 external/gptfdisk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/guava --depth 1 external/guava  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/guice --depth 1 external/guice  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/hamcrest --depth 1 external/hamcrest  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/harfbuzz_ng --depth 1 external/harfbuzz_ng  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/honggfuzz --depth 1 external/honggfuzz  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/hyphenation-patterns --depth 1 external/hyphenation-patterns  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/icu --depth 1 external/icu  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ImageMagick --depth 1 external/ImageMagick  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ims --depth 1 external/ims  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/iproute2 --depth 1 external/iproute2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ipsec-tools --depth 1 external/ipsec-tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/iptables --depth 1 external/iptables  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/iputils --depth 1 external/iputils  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/iw --depth 1 external/iw  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jacoco --depth 1 external/jacoco  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jarjar --depth 1 external/jarjar  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/javaparser --depth 1 external/javaparser  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/javasqlite --depth 1 external/javasqlite  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/javassist --depth 1 external/javassist  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jcommander --depth 1 external/jcommander  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jdiff --depth 1 external/jdiff  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jemalloc --depth 1 external/jemalloc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jmdns --depth 1 external/jmdns  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jsilver --depth 1 external/jsilver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jsmn --depth 1 external/jsmn  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jsoncpp --depth 1 external/jsoncpp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jsr305 --depth 1 external/jsr305  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/jsr330 --depth 1 external/jsr330  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/junit --depth 1 external/junit  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/junit-params --depth 1 external/junit-params  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/kernel-headers --depth 1 external/kernel-headers  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/kmod --depth 1 external/kmod  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/kotlinc --depth 1 external/kotlinc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ksoap2 --depth 1 external/ksoap2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libavc --depth 1 external/libavc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libbackup --depth 1 external/libbackup  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libbrillo --depth 1 external/libbrillo  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libcap --depth 1 external/libcap  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libcap-ng --depth 1 external/libcap-ng  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libchrome --depth 1 external/libchrome  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libconstrainedcrypto --depth 1 external/libconstrainedcrypto  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libcups --depth 1 external/libcups  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libcxx --depth 1 external/libcxx  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libcxxabi --depth 1 external/libcxxabi  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libdaemon --depth 1 external/libdaemon  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libdivsufsort --depth 1 external/libdivsufsort  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libese --depth 1 external/libese  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libevent --depth 1 external/libevent  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libexif --depth 1 external/libexif  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libffi --depth 1 external/libffi  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libgsm --depth 1 external/libgsm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libhevc --depth 1 external/libhevc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libjpeg-turbo --depth 1 external/libjpeg-turbo  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libldac --depth 1 external/libldac  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libmicrohttpd --depth 1 external/libmicrohttpd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libmojo --depth 1 external/libmojo  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libmpeg2 --depth 1 external/libmpeg2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libmtp --depth 1 external/libmtp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libnetfilter_conntrack --depth 1 external/libnetfilter_conntrack  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libnfnetlink --depth 1 external/libnfnetlink  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libnl --depth 1 external/libnl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libogg --depth 1 external/libogg  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libopus --depth 1 external/libopus  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libpcap --depth 1 external/libpcap  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libphonenumber --depth 1 external/libphonenumber  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libpng --depth 1 external/libpng  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libtextclassifier --depth 1 external/libtextclassifier  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libunwind --depth 1 external/libunwind  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libunwind_llvm --depth 1 external/libunwind_llvm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libusb --depth 1 external/libusb  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libvncserver --depth 1 external/libvncserver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libvpx --depth 1 external/libvpx  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libvterm --depth 1 external/libvterm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libxaac --depth 1 external/libxaac  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libxcam --depth 1 external/libxcam  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libxkbcommon --depth 1 external/libxkbcommon  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libxml2 --depth 1 external/libxml2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/libyuv --depth 1 external/libyuv  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/linux-kselftest --depth 1 external/linux-kselftest  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/lisa --depth 1 external/lisa  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/llvm --depth 1 external/llvm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/lmfit --depth 1 external/lmfit  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ltp --depth 1 external/ltp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/lz4 --depth 1 external/lz4  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/lzma --depth 1 external/lzma  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/markdown --depth 1 external/markdown  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mdnsresponder --depth 1 external/mdnsresponder  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/Microsoft-GSL --depth 1 external/Microsoft-GSL  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/minijail --depth 1 external/minijail  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mmc-utils --depth 1 external/mmc-utils  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mockftpserver --depth 1 external/mockftpserver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mockito --depth 1 external/mockito  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mockwebserver --depth 1 external/mockwebserver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/modp_b64 --depth 1 external/modp_b64  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mp4parser --depth 1 external/mp4parser  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/mtpd --depth 1 external/mtpd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nanohttpd --depth 1 external/nanohttpd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nanopb-c --depth 1 external/nanopb-c  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/naver-fonts --depth 1 external/naver-fonts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/netcat --depth 1 external/netcat  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/neven --depth 1 external/neven  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nfacct --depth 1 external/nfacct  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nist-pkits --depth 1 external/nist-pkits  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nist-sip --depth 1 external/nist-sip  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nos/host/android --depth 1 external/nos/host/android  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nos/host/generic --depth 1 external/nos/host/generic  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/nos/test/system-test-harness --depth 1 external/nos/test/system-test-harness  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/noto-fonts --depth 1 external/noto-fonts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/oauth --depth 1 external/oauth  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/objenesis --depth 1 external/objenesis  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/oj-libjdwp --depth 1 external/oj-libjdwp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/okhttp --depth 1 external/okhttp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/one-true-awk --depth 1 external/one-true-awk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/owasp/sanitizer --depth 1 external/owasp/sanitizer  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/parameter-framework --depth 1 external/parameter-framework  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/pcre --depth 1 external/pcre  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/pdfium --depth 1 external/pdfium  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/perf_data_converter --depth 1 external/perf_data_converter  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/perfetto --depth 1 external/perfetto  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/piex --depth 1 external/piex  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ply --depth 1 external/ply  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/ppp --depth 1 external/ppp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/proguard --depth 1 external/proguard  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/protobuf --depth 1 external/protobuf  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/puffin --depth 1 external/puffin  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/appdirs --depth 1 external/python/appdirs  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/cachetools --depth 1 external/python/cachetools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/cpython2 --depth 1 external/python/cpython2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/cpython3 --depth 1 external/python/cpython3  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/dill --depth 1 external/python/dill  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/enum --depth 1 external/python/enum  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/enum34 --depth 1 external/python/enum34  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/future --depth 1 external/python/future  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/futures --depth 1 external/python/futures  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/gapic-google-cloud-pubsub-v1 --depth 1 external/python/gapic-google-cloud-pubsub-v1  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/google-api-python-client --depth 1 external/python/google-api-python-client  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/google-auth --depth 1 external/python/google-auth  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/google-auth-httplib2 --depth 1 external/python/google-auth-httplib2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/google-cloud-core --depth 1 external/python/google-cloud-core  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/google-cloud-pubsub --depth 1 external/python/google-cloud-pubsub  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/google-gax --depth 1 external/python/google-gax  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/googleapis --depth 1 external/python/googleapis  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/grpc-google-iam-v1 --depth 1 external/python/grpc-google-iam-v1  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/grpcio --depth 1 external/python/grpcio  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/httplib2 --depth 1 external/python/httplib2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/matplotlib --depth 1 external/python/matplotlib  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/numpy --depth 1 external/python/numpy  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/oauth2client --depth 1 external/python/oauth2client  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/olefile --depth 1 external/python/olefile  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/packaging --depth 1 external/python/packaging  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/parse --depth 1 external/python/parse  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/Pillow --depth 1 external/python/Pillow  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/ply --depth 1 external/python/ply  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/proto-google-cloud-pubsub-v1 --depth 1 external/python/proto-google-cloud-pubsub-v1  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/protobuf --depth 1 external/python/protobuf  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/pyasn1 --depth 1 external/python/pyasn1  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/pyasn1-modules --depth 1 external/python/pyasn1-modules  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/pyparsing --depth 1 external/python/pyparsing  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/requests --depth 1 external/python/requests  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/rsa --depth 1 external/python/rsa  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/scipy --depth 1 external/python/scipy  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/setuptools --depth 1 external/python/setuptools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/six --depth 1 external/python/six  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/python/uritemplates --depth 1 external/python/uritemplates  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/rappor --depth 1 external/rappor  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/replicaisland --depth 1 external/replicaisland  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/rmi4utils --depth 1 external/rmi4utils  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/robolectric --depth 1 external/robolectric  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/robolectric-shadows --depth 1 external/robolectric-shadows  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/roboto-fonts --depth 1 external/roboto-fonts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/rootdev --depth 1 external/rootdev  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/safe-iop --depth 1 external/safe-iop  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/scapy --depth 1 external/scapy  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/scrypt --depth 1 external/scrypt  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/seccomp-tests --depth 1 external/seccomp-tests  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/selinux --depth 1 external/selinux  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/sfntly --depth 1 external/sfntly  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/shaderc/spirv-headers --depth 1 external/shaderc/spirv-headers  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/shflags --depth 1 external/shflags  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/skia --depth 1 external/skia  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/skqp --depth 1 external/skqp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/sl4a --depth 1 external/sl4a  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/slf4j --depth 1 external/slf4j  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/smali --depth 1 external/smali  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/snakeyaml --depth 1 external/snakeyaml  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/sonic --depth 1 external/sonic  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/sonivox --depth 1 external/sonivox  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/speex --depth 1 external/speex  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/spirv-llvm --depth 1 external/spirv-llvm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/sqlite --depth 1 external/sqlite  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/squashfs-tools --depth 1 external/squashfs-tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/strace --depth 1 external/strace  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/stressapptest --depth 1 external/stressapptest  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/subsampling-scale-image-view --depth 1 external/subsampling-scale-image-view  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/syslinux --depth 1 external/syslinux  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tagsoup --depth 1 external/tagsoup  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tcpdump --depth 1 external/tcpdump  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tensorflow --depth 1 external/tensorflow  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/testng --depth 1 external/testng  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/timezonepicker-support --depth 1 external/timezonepicker-support  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tinyalsa --depth 1 external/tinyalsa  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tinycompress --depth 1 external/tinycompress  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tinyxml --depth 1 external/tinyxml  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tinyxml2 --depth 1 external/tinyxml2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/toolchain-utils --depth 1 external/toolchain-utils  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/toybox --depth 1 external/toybox  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tpm2 --depth 1 external/tpm2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/trappy --depth 1 external/trappy  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/tremolo --depth 1 external/tremolo  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/turbine --depth 1 external/turbine  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/unicode --depth 1 external/unicode  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/universal-tween-engine --depth 1 external/universal-tween-engine  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/v4l2_codec2 --depth 1 external/v4l2_codec2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/v8 --depth 1 external/v8  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/valgrind --depth 1 external/valgrind  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/vboot_reference --depth 1 external/vboot_reference  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/vixl --depth 1 external/vixl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/vogar --depth 1 external/vogar  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/volley --depth 1 external/volley  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/vulkan-validation-layers --depth 1 external/vulkan-validation-layers  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/walt --depth 1 external/walt  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/wayland --depth 1 external/wayland  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/wayland-protocols --depth 1 external/wayland-protocols  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/webp --depth 1 external/webp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/webrtc --depth 1 external/webrtc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/webview_support_interfaces --depth 1 external/webview_support_interfaces  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/wpa_supplicant_8 --depth 1 external/wpa_supplicant_8  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/wycheproof --depth 1 external/wycheproof  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/x264 --depth 1 external/x264  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/xmlrpcpp --depth 1 external/xmlrpcpp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/xmp_toolkit --depth 1 external/xmp_toolkit  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/xz-embedded --depth 1 external/xz-embedded  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/zlib --depth 1 external/zlib  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/zopfli --depth 1 external/zopfli  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/external/zxing --depth 1 external/zxing  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/compile/libbcc --depth 1 frameworks/compile/libbcc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/compile/mclinker --depth 1 frameworks/compile/mclinker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/compile/slang --depth 1 frameworks/compile/slang  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/data-binding --depth 1 frameworks/data-binding  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/ex --depth 1 frameworks/ex  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/hardware/interfaces --depth 1 frameworks/hardware/interfaces  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/layoutlib --depth 1 frameworks/layoutlib  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/minikin --depth 1 frameworks/minikin  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/ml --depth 1 frameworks/ml  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/multidex --depth 1 frameworks/multidex  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/bitmap --depth 1 frameworks/opt/bitmap  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/calendar --depth 1 frameworks/opt/calendar  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/car/services --depth 1 frameworks/opt/car/services  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/chips --depth 1 frameworks/opt/chips  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/colorpicker --depth 1 frameworks/opt/colorpicker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/datetimepicker --depth 1 frameworks/opt/datetimepicker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/inputconnectioncommon --depth 1 frameworks/opt/inputconnectioncommon  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/inputmethodcommon --depth 1 frameworks/opt/inputmethodcommon  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/net/ethernet --depth 1 frameworks/opt/net/ethernet  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/net/ims --depth 1 frameworks/opt/net/ims  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/net/lowpan --depth 1 frameworks/opt/net/lowpan  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/net/voip --depth 1 frameworks/opt/net/voip  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/net/wifi --depth 1 frameworks/opt/net/wifi  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/photoviewer --depth 1 frameworks/opt/photoviewer  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/setupwizard --depth 1 frameworks/opt/setupwizard  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/telephony --depth 1 frameworks/opt/telephony  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/timezonepicker --depth 1 frameworks/opt/timezonepicker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/opt/vcard --depth 1 frameworks/opt/vcard  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/rs --depth 1 frameworks/rs  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/support --depth 1 frameworks/support  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/frameworks/wilhelm --depth 1 frameworks/wilhelm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/hardware/google/apf --depth 1 hardware/google/apf  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/hardware/interfaces --depth 1 hardware/interfaces  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/hardware/libhardware --depth 1 hardware/libhardware  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/hardware/libhardware_legacy --depth 1 hardware/libhardware_legacy  -b android-9.0.0_r61 
git clone https://android.googlesource.com/kernel/configs --depth 1 kernel/configs  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/libcore --depth 1 libcore  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/libnativehelper --depth 1 libnativehelper  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/BasicSmsReceiver --depth 1 packages/apps/BasicSmsReceiver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Bluetooth --depth 1 packages/apps/Bluetooth  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Browser2 --depth 1 packages/apps/Browser2  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Calendar --depth 1 packages/apps/Calendar  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Car/libs --depth 1 packages/apps/Car/libs  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/CarrierConfig --depth 1 packages/apps/CarrierConfig  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/CellBroadcastReceiver --depth 1 packages/apps/CellBroadcastReceiver  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/CertInstaller --depth 1 packages/apps/CertInstaller  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Contacts --depth 1 packages/apps/Contacts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/DeskClock --depth 1 packages/apps/DeskClock  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/DevCamera --depth 1 packages/apps/DevCamera  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Dialer --depth 1 packages/apps/Dialer  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/DocumentsUI --depth 1 packages/apps/DocumentsUI  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Email --depth 1 packages/apps/Email  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/EmergencyInfo --depth 1 packages/apps/EmergencyInfo  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/ExactCalculator --depth 1 packages/apps/ExactCalculator  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/HTMLViewer --depth 1 packages/apps/HTMLViewer  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/KeyChain --depth 1 packages/apps/KeyChain  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Launcher3 --depth 1 packages/apps/Launcher3  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/ManagedProvisioning --depth 1 packages/apps/ManagedProvisioning  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Messaging --depth 1 packages/apps/Messaging  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/OneTimeInitializer --depth 1 packages/apps/OneTimeInitializer  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/PackageInstaller --depth 1 packages/apps/PackageInstaller  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/PhoneCommon --depth 1 packages/apps/PhoneCommon  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Protips --depth 1 packages/apps/Protips  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Provision --depth 1 packages/apps/Provision  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/QuickSearchBox --depth 1 packages/apps/QuickSearchBox  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/SafetyRegulatoryInfo --depth 1 packages/apps/SafetyRegulatoryInfo  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/SettingsIntelligence --depth 1 packages/apps/SettingsIntelligence  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/SoundRecorder --depth 1 packages/apps/SoundRecorder  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/SpareParts --depth 1 packages/apps/SpareParts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Stk --depth 1 packages/apps/Stk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/StorageManager --depth 1 packages/apps/StorageManager  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Terminal --depth 1 packages/apps/Terminal  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/TimeZoneData --depth 1 packages/apps/TimeZoneData  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/TimeZoneUpdater --depth 1 packages/apps/TimeZoneUpdater  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/Traceur --depth 1 packages/apps/Traceur  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/UnifiedEmail --depth 1 packages/apps/UnifiedEmail  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/apps/WallpaperPicker --depth 1 packages/apps/WallpaperPicker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/inputmethods/LatinIME --depth 1 packages/inputmethods/LatinIME  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/ApplicationsProvider --depth 1 packages/providers/ApplicationsProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/BlockedNumberProvider --depth 1 packages/providers/BlockedNumberProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/BookmarkProvider --depth 1 packages/providers/BookmarkProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/CalendarProvider --depth 1 packages/providers/CalendarProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/CallLogProvider --depth 1 packages/providers/CallLogProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/ContactsProvider --depth 1 packages/providers/ContactsProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/DownloadProvider --depth 1 packages/providers/DownloadProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/MediaProvider --depth 1 packages/providers/MediaProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/PartnerBookmarksProvider --depth 1 packages/providers/PartnerBookmarksProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/TelephonyProvider --depth 1 packages/providers/TelephonyProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/TvProvider --depth 1 packages/providers/TvProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/providers/UserDictionaryProvider --depth 1 packages/providers/UserDictionaryProvider  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/screensavers/Basic --depth 1 packages/screensavers/Basic  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/screensavers/PhotoTable --depth 1 packages/screensavers/PhotoTable  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/screensavers/WebView --depth 1 packages/screensavers/WebView  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/services/BuiltInPrintService --depth 1 packages/services/BuiltInPrintService  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/services/Car --depth 1 packages/services/Car  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/services/Mms --depth 1 packages/services/Mms  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/services/NetworkRecommendation --depth 1 packages/services/NetworkRecommendation  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/services/Telephony --depth 1 packages/services/Telephony  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/packages/wallpapers/LivePicker --depth 1 packages/wallpapers/LivePicker  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/pdk --depth 1 pdk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/platform_testing --depth 1 platform_testing  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/abi-dumps/ndk --depth 1 prebuilts/abi-dumps/ndk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/abi-dumps/vndk --depth 1 prebuilts/abi-dumps/vndk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/build-tools --depth 1 prebuilts/build-tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/checkcolor --depth 1 prebuilts/checkcolor  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/checkstyle --depth 1 prebuilts/checkstyle  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/clang-tools --depth 1 prebuilts/clang-tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/clang/host/darwin-x86 --depth 1 prebuilts/clang/host/darwin-x86  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth 1 prebuilts/clang/host/linux-x86  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/deqp --depth 1 prebuilts/deqp  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/devtools --depth 1 prebuilts/devtools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/host/i686-apple-darwin-4.2.1 --depth 1 prebuilts/gcc/darwin-x86/host/i686-apple-darwin-4.2.1  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.9 --depth 1 prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.9  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.6 --depth 1 prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.6  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8 --depth 1 prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9 --depth 1 prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gdb/darwin-x86 --depth 1 prebuilts/gdb/darwin-x86  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gdb/linux-x86 --depth 1 prebuilts/gdb/linux-x86  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/go/darwin-x86 --depth 1 prebuilts/go/darwin-x86  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/go/linux-x86 --depth 1 prebuilts/go/linux-x86  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/gradle-plugin --depth 1 prebuilts/gradle-plugin  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/jdk/jdk8 --depth 1 prebuilts/jdk/jdk8  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/jdk/jdk9 --depth 1 prebuilts/jdk/jdk9  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/maven_repo/android --depth 1 prebuilts/maven_repo/android  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/maven_repo/bumptech --depth 1 prebuilts/maven_repo/bumptech  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/misc --depth 1 prebuilts/misc  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/ndk --depth 1 prebuilts/ndk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/ktlint --depth 1 prebuilts/ktlint  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/python/darwin-x86/2.7.5 --depth 1 prebuilts/python/darwin-x86/2.7.5  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/python/linux-x86/2.7.5 --depth 1 prebuilts/python/linux-x86/2.7.5  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/r8 --depth 1 prebuilts/r8  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/sdk --depth 1 prebuilts/sdk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/tools --depth 1 prebuilts/tools  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/prebuilts/vndk/v27 --depth 1 prebuilts/vndk/v27  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/sdk --depth 1 sdk  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/ca-certificates --depth 1 system/ca-certificates  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/chre --depth 1 system/chre  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/connectivity/wificond --depth 1 system/connectivity/wificond  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/connectivity/wifilogd --depth 1 system/connectivity/wifilogd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/gatekeeper --depth 1 system/gatekeeper  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/hardware/interfaces --depth 1 system/hardware/interfaces  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/hwservicemanager --depth 1 system/hwservicemanager  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/iot/attestation --depth 1 system/iot/attestation  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/keymaster --depth 1 system/keymaster  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/libfmq --depth 1 system/libfmq  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/libhidl --depth 1 system/libhidl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/libhwbinder --depth 1 system/libhwbinder  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/libufdt --depth 1 system/libufdt  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/libvintf --depth 1 system/libvintf  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/netd --depth 1 system/netd  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/nvram --depth 1 system/nvram  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/security --depth 1 system/security  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/sepolicy --depth 1 system/sepolicy  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/timezone --depth 1 system/timezone  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/tools/aidl --depth 1 system/tools/aidl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/tools/hidl --depth 1 system/tools/hidl  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/tpm --depth 1 system/tpm  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/system/update_engine --depth 1 system/update_engine  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/test/suite_harness --depth 1 test/suite_harness  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/test/vts --depth 1 test/vts  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/test/vts-testcase/hal-trace --depth 1 test/vts-testcase/hal-trace  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/test/vts-testcase/performance --depth 1 test/vts-testcase/performance  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/adt/idea --depth 1 tools/adt/idea  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/apksig --depth 1 tools/apksig  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/base --depth 1 tools/base  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/build --depth 1 tools/build  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/dexter --depth 1 tools/dexter  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/idea --depth 1 tools/idea  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/metalava --depth 1 tools/metalava  -b android-9.0.0_r61 
git clone https://android.googlesource.com/platform/tools/test/connectivity --depth 1 tools/test/connectivity  -b android-9.0.0_r61 
