git clone https://scm.osdn.net/gitroot/android-x86/kernel/common --depth 1 kernel  -b kernel-4.19
git clone https://scm.osdn.net/gitroot/android-x86/platform/bionic --depth 1 bionic  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/bootable/newinstaller --depth 1 bootable/newinstaller  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/device/generic/common --depth 1 device/generic/common  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/device/generic/firmware --depth 1 device/generic/firmware  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/device/generic/x86_64 --depth 1 device/generic/x86_64  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/device/generic/x86 --depth 1 device/generic/x86  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/IA-Hardware-Composer --depth 1 external/IA-Hardware-Composer  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/alsa-lib --depth 1 external/alsa-lib  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/alsa-ucm-conf --depth 1 external/alsa-ucm-conf  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/alsa-utils --depth 1 external/alsa-utils  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/bluetooth/bluez --depth 1 external/bluetooth/bluez  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/busybox --depth 1 external/busybox  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/drm_framebuffer --depth 1 external/drm_framebuffer  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/drm_gralloc --depth 1 external/drm_gralloc  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/drm_hwcomposer --depth 1 external/drm_hwcomposer  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/drmfb-composer --depth 1 external/drmfb-composer  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/efibootmgr --depth 1 external/efibootmgr  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/efivar --depth 1 external/efivar  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/exfat --depth 1 external/exfat  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/ffmpeg --depth 1 external/ffmpeg  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/gbm_gralloc --depth 1 external/gbm_gralloc  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/googleanalytics --depth 1 external/googleanalytics  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/kernel-drivers --depth 1 external/kernel-drivers  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/koush/Superuser --depth 1 external/koush/Superuser  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/koush/Widgets --depth 1 external/koush/Widgets  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/libdrm --depth 1 external/libdrm  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/libncurses --depth 1 external/libncurses  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/llvm-project --depth 1 external/llvm-project  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/mesa --depth 1 external/mesa  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/minigbm --depth 1 external/minigbm  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/minigbm --depth 1 external/minigbm_intel  -b pie-x86_intel
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/mksh --depth 1 external/mksh  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/ntfs-3g --depth 1 external/ntfs-3g  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/openssh --depth 1 external/openssh  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/s2tc --depth 1 external/s2tc  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/stagefright-plugins --depth 1 external/stagefright-plugins  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/swiftshader --depth 1 external/swiftshader  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/external/v86d --depth 1 external/v86d  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/frameworks/av --depth 1 frameworks/av  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/frameworks/base --depth 1 frameworks/base  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/frameworks/native --depth 1 frameworks/native  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/gps --depth 1 hardware/gps  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/intel/audio_media --depth 1 hardware/intel/audio_media  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/intel/common/libva --depth 1 hardware/intel/common/libva  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/intel/common/vaapi --depth 1 hardware/intel/common/vaapi  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/intel/libsensors --depth 1 hardware/intel/libsensors  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/libaudio --depth 1 hardware/libaudio  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/libcamera --depth 1 hardware/libcamera  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/liblights --depth 1 hardware/liblights  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/libsensors --depth 1 hardware/libsensors  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/memtrack --depth 1 hardware/memtrack  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/ril --depth 1 hardware/ril  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/hardware/x86power --depth 1 hardware/x86power  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/apps/Camera2 --depth 1 packages/apps/Camera2  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/apps/Eleven --depth 1 packages/apps/Eleven  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/apps/Gallery2 --depth 1 packages/apps/Gallery2  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/apps/Settings --depth 1 packages/apps/Settings  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/apps/Taskbar --depth 1 packages/apps/Taskbar  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/apps/TSCalibration2 --depth 1 packages/apps/TSCalibration2  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/packages/services/Analytics --depth 1 packages/services/Analytics  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/system/bt --depth 1 system/bt  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/system/core --depth 1 system/core  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/system/extras --depth 1 system/extras  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/system/media --depth 1 system/media  -b pie-x86
git clone https://scm.osdn.net/gitroot/android-x86/platform/system/vold --depth 1 system/vold  -b pie-x86
